jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
    maxParallel: 2

  steps:
  - task: NodeTool@0
    inputs:
      version: $(node_version)
   
  - script: |
      npm install
      npm run vscode:prepublish
  
  - script: |
      npm run tslint

  - script: |
      npm test --silent
    condition: ne(variables['Agent.OS'], 'Linux')